name: Unittest

on:
  push:
    branches:
      - master
      - release/*

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        # setup-python stopped supporting Python 2.7, use https://github.com/MatteoH2O1999/setup-python
        # This action tries to build all Python versions that actions/setup-python does not support.
        # It caches built versions, so that after the first run, installation time is really low.
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pytest pytest-cov codecov mock
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest tests/ --cov=testbase --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: true
            files: ./coverage.xml
            flags: unittests
            name: codecov-qtaf
            path_to_write_report: ./coverage/codecov_report.txt
            verbose: true

